services:
  web:
    build: .
    ports:
      - "8989:8989"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "mysql"
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE= "MyDb"
      - MYSQL_USER= "root"
      - MYSQL_PASSWORD= "passroot"
      - MYSQL_RANDOM_ROOT_PASSWORD= "1"